<!DOCTYPE html>
<html>
<head>
    <style>
        /* PDF Page Split Logic */
        .page-break {
            page-break-after: always;
        }
        /* Last page par extra khali page na aaye isliye */
        .page-break:last-child {
            page-break-after: never;
        }

        body { font-family: 'Helvetica', sans-serif; color: #333; font-size: 12px; margin: 0; padding: 0; }
        .order-container { padding: 20px; }
        .header { text-align: center; margin-bottom: 20px; border-bottom: 2px solid #D4AF37; padding-bottom: 10px; }
        .brand { color: #D4AF37; font-size: 22px; font-weight: bold; margin: 0; }
        
        .order-info { margin-bottom: 15px; width: 100%; }
        .order-info td { padding: 2px 0; }

        table.items-table { width: 100%; border-collapse: collapse; margin-top: 10px; }
        table.items-table th { background-color: #f8f9fa; padding: 8px; border: 1px solid #ddd; text-align: left; }
        table.items-table td { padding: 8px; border: 1px solid #ddd; }
        
        .footer { position: fixed; bottom: 10px; width: 100%; text-align: center; font-size: 9px; color: #999; }
    </style>
</head>
<body>

    @foreach($orders as $order)
        <div class="order-container {{ !$loop->last ? 'page-break' : '' }}">
            <div class="header">
                <h1 class="brand">Fleetshyp</h1>
                <div style="font-size: 13px; font-weight: bold; margin-top: 5px;">PICKLIST / PACKING SLIP</div>
            </div>

            <table class="order-info">
                <tr>
                    <td width="50%"><strong>Order ID:</strong> #{{ $order->merchant_order_id }}</td>
                    <td width="50%" align="right"><strong>Date:</strong> {{ date('d-M-Y h:i A') }}</td>
                </tr>
                <tr>
                    <td><strong>Customer:</strong> {{ $order->buyer_name }}</td>
                    <td align="right"><strong>Phone:</strong> {{ $order->phone_number }}</td>
                </tr>
            </table>

            <table class="items-table">
                <thead>
                    <tr>
                        <th width="50%">Product Name</th>
                        <th width="30%">SKU</th>
                        <th width="20%">Quantity</th>
                    </tr>
                </thead>
                <tbody>
                    @php $itemCount = 0; @endphp
                    @foreach($order->items as $item)
                        <tr>
                            <td>{{ $item->product_name }}</td>
                            <td>{{ $item->sku ?? 'N/A' }}</td>
                            <td>{{ $item->quantity }}</td>
                        </tr>
                        @php $itemCount += $item->quantity; @endphp
                    @endforeach
                </tbody>
            </table>

            <div style="margin-top: 15px; text-align: right;">
                <strong>Total Items in this Order: {{ $itemCount }}</strong>
            </div>
            
            <div style="margin-top: 50px; border-top: 1px dashed #ccc; padding-top: 10px;">
                <p style="font-size: 10px; color: #666;">Note: Please check items carefully before packing.</p>
            </div>
        </div>
    @endforeach

    <div class="footer">
        Fleetshyp Logistics - Generated by {{ Auth::user()->name }}
    </div>

</body>
</html>